spring.application.name=gesfun-bff
server.port=8081

spring.security.oauth2.resourceserver.jwt.issuer-uri=https://sts.windows.net/0848441e-8d61-4f58-84b7-9f55266c7ee4/

spring.security.oauth2.resourceserver.jwt.audience=https://duocactividadazure.onmicrosoft.com/daead1c3-a4cc-4647-9423-e1fc626d8003

backend.base-url=http://localhost:8080
cors.allowed-origins=http://localhost:4200
