spring.application.name=gesfun-bff
server.port=8081

spring.security.oauth2.resourceserver.jwt.issuer-uri=https://login.microsoftonline.com/0848441e-8d61-4f58-84b7-9f55266c7ee4/v2.0

spring.security.oauth2.resourceserver.jwt.audience=daead1c3-a4cc-4647-9423-e1fc626d8003
security.jwt.allowed-client-ids=7c4068b3-4cdf-42f3-84ac-f8e2d2042118,e0090ab4-8924-4d8e-a5be-3edca3ebe556

backend.base-url=http://localhost:8080
cors.allowed-origins=http://localhost:4200
